### ISSUE TITLE
Drop `bluebird`

### ISSUE THREAD

**Issue by alexander-akait** [zkat/cacache#135]
Node@6 support promises, no need this library

**Comment by zkat** [comment]
I use way more than just `Bluebird.promisify`. I'm not interested in reimplementing all the iteration and multi-selection utilities and rewrite a significant chunk of the code just to get rid of a single library that's not really adding a lot of weight at the npm level (since so many other things use it, too, so it's deduped)

**Comment by chaffeqa** [comment]
great to clean dependencies of Bluebird in our project.  Especially given node LTS support for native promises now.

A [bunch of libs](https://github.com/OptimalBits/bull/pull/1156) are successfully moving from bluebird using stuff like `utils-promisify`.

I'd love to help out if you are interested!
